[package]
name = "omoria"
version = "0.1.0"
authors = ["Olle Kvarnstr√∂m <olle+git@iix.se>"]

[dependencies]
libc = "0.2"
rand = "0.4"

[lib]
name = "omoria"
crate-type = ["staticlib"]
path = "src/lib.rs"
